version: '2.2'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /Users/hwang/DataRepo/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    cpus: '1'
    mem_limit: '2G'
    ports:
      - "27017:27017"
    command: ["mongod"]
    networks:
      mongo-net:

networks:
  mongo-net: